### ISSUE TITLE
Possible guide to navigate your code.

### ISSUE THREAD

**Issue by slythethieve2** [IGGAMEMAKER/Corporations#1]
Hi, I was wondering if you could maybe give a brief overview on the structure of your code. I have to say it is quite massive.

Thank you very much.

**Comment by IGGAMEMAKER** [comment]
Hi, who are you and how did you find my project?

My code structure is really messy, cause I'm doing this project alone and feature list is changing fast

**Comment by slythethieve2** [comment]
Hi, I'm an economics students from Switzerland. In one of my seminars I chose to develop a small game to help professors teach corporate finance concepts more easily. I stumbled upon your project by pure chance, when I was searching for Business simulators to get some ideas on how to implement certain features.

**Comment by IGGAMEMAKER** [comment]
Wow, cool! I'll explain my code structure tommorow

**Comment by slythethieve2** [comment]
Thank you very much. Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: gaga <notifications@github.com> Data: 26/10/19  23:39  (GMT+01:00) A: IGGAMEMAKER/Corporations <Corporations@noreply.github.com> Cc: slythethieve2 <matteo.ds01@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [IGGAMEMAKER/Corporations] Possible guide to navigate your code. (#1) Wow, cool! I'll explain my code structure tommorow

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/IGGAMEMAKER/Corporations/issues/1?email_source=notifications\u0026email_token=ANQEAH65H4PUJ6PP3LVGIHLQQS2HTA5CNFSM4JBLHUUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECKROYY#issuecomment-546641763",
"url": "https://github.com/IGGAMEMAKER/Corporations/issues/1?email_source=notifications\u0026email_token=ANQEAH65H4PUJ6PP3LVGIHLQQS2HTA5CNFSM4JBLHUUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECKROYY#issuecomment-546641763",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by IGGAMEMAKER** [comment]
My code is a piece of shit, that just works. You won't find any advanced technique here, but I'll describe my code anyway:

1. I'm using Entitas ECS framework for manipulating data.
- Components are located in Assets/Components
- and Systems are located in Assets/Systems
Both of these folders are splitted by features, aka: Systems/AI or Systems/Acquisitions e.t.c.

Entitas files are located in Assets/Libraries and Assets/Generated

2. All view components are simply placed in Assets folder
Most of them are inherited from Assets/BaseClasses/View/View.cs class

To refresh these view components, you just simply need to put Assets/BaseClasses/LazyUpdate.cs script alongside with them.
When player clicks a button, LazyUpdate triggers ViewRender method of View.cs component and component redraws.

3. Most important folders are:

- Assets/BaseClasses - contains a lot of inheritable classes
- Assets/Utils - contains most of game logic (queries and model updates). Tbh, this should be named as Assets/Models
- Assets/Screens - This game contains all game screen prefabs
